---
docker/aufs-tools_20120411-3_amd64.deb:
  object_id: d8788377-d011-438e-a151-f2971841977e
  sha: !binary |-
    MmRmYzFmZTM4NmNkM2YwNWFjN2UwYjRlYmNmM2ViYzhhN2YzYjA0ZA==
  size: 91762
docker/bridge-utils-1.5.tar.gz:
  object_id: 79652021-e3b0-483a-ac9d-2e052678a878
  sha: !binary |-
    MWY3MWI2ZjIyZjVkMmI2ZDIxZTE0NmY0YWMyMDgyMGFkNDJlNThlZQ==
  size: 33472
docker/docker-1.11.0.tgz:
  object_id: 1104a156-f916-466c-9d80-4beb430f24a4
  sha: !binary |-
    MjQyYjZhM2U2ZGVmNjcxOWY1MDAyYTRkM2Q1YjM1ZTU4NzAzNmM0ZQ==
  size: 20520756
docker/autoconf-2.69.tar.gz:
  object_id: 40946190-ab70-4eb3-a4cc-d2901440e181
  sha: !binary |-
    NTYyNDcxY2JjYjBkZDBmYTQyYTc2NjY1YWNmMGRiYjY4NDc5Yjc4YQ==
  size: 1927468
