releases:
- name: docker
  version: latest
- name: logsearch-cf-dashboards
  version: latest

properties:
  docker:
    tcp_address: 0.0.0.0
    port: 4243
    tls: true
    tls_verify: true
  elasticsearch:
    host: (( merge ))
    port: (( merge ))
  remote-docker:
    host: (( jobs.elasticdump.networks.default.static_ips ))
    port: (( .properties.docker.port ))

networks: (( merge ))

jobs:
- name: elasticdump
  templates:
  - name: docker
    release: docker
  - name: just_install_dashboards
    release: logsearch-cf-dashboards
  - name: taskrabbit_elasticsearch_dump_image
    release: logsearch-cf-dashboards
  instances: 1
  resource_pool: small_z1
  persistent_disk: 10400
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
    
- name: export
  templates:
  - name: export_dashboard
    release: logsearch-cf-dashboards
  instances: 1
  resource_pool: small_z1
  lifecycle: errand
  networks:
  - name: default
    static_ips: (( static_ips(1) ))

- name: import
  templates:
  - name: import_dashboard
    release: logsearch-cf-dashboards
  instances: 1
  resource_pool: small_z1
  lifecycle: errand
  networks:
  - name: default
    static_ips: (( static_ips(2) ))
